name: Deploy document

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: build documents
        run: |
          sudo gem install asciidoctor
          sudo gem install asciidoctor-diagram

          mkdir -p /usr/share/fonts/VLGothic
          cp ./documents/assets/VL-Gothic-Regular.ttf /usr/share/fonts/VLGothic

          ./bin/build.sh
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
